#!/bin/sh
### BEGIN INIT INFO
# Provides:		 yauj_daemon
# Required-Start:	 
# Required-Stop:	
# Default-Start:	 2 3 4 5
# Default-Stop:		 0 1 6
# Short-Description: Provide Judge Daemon for YAUJ
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

PROG="yauj_daemon"
PROG_PATH="/usr/bin"

start() {
	sudo -u www-data $PROG_PATH/$PROG >/dev/null 2>&1 &
}

stop() {
	killall $PROG
}

if [ `id -u` != "0" ]; then
	echo "Please run as ROOT!" 1>&2
	exit 1
fi

case "$1" in
  start)
	start
	;;
  restart)
	stop
	start
	;;
  stop)
	stop
	;;
  **)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
