<?php
	$config['use_page_numbers'] = TRUE;
	$config['full_tag_open'] = '<div class="pagination pagination-small pagination-centered"><ul>';
	$config['full_tag_close'] = '</ul></div>';
	$config['first_tag_open'] = '<li>';
	$config['first_tag_close'] = '</li>';
	$config['last_tag_open'] = '<li>';
	$config['last_tag_close'] = '</li>';
	$config['next_tag_open'] = '<li>';
	$config['next_tag_close'] = '</li>';
	$config['prev_tag_open'] = '<li>';
	$config['prev_tag_close'] = '</li>';
	$config['num_tag_open'] = '<li>';
	$config['num_tag_close'] = '</li>';
	$config['cur_tag_open'] = '<li><a><strong>';
	$config['cur_tag_close'] = '</strong></a></li>';
	$config['first_link'] = '<<';
	$config['last_link'] = '>>';
	$config['prev_link'] = '<';
	$config['next_link'] = '>';
	$config['num_links'] = 7;